[workspace]
members = [
    "consensus",
    "crypto",
    "config",
    "pospace",
    "node",
    "grpc",
    "storage",
    "network",
    "mempool",
    "ledger",
    "ledger/merkle-tree",
]

[profile.release]
debug = true

[profile.bench]
debug = true