[workspace]
members = [
    "crypto",
    "pospace",
    "node",
    "grpc",
    "storage",
    "ledger",
    "merkletree",
    "powork",
]

[profile.release]
debug = true

[profile.bench]
debug = true