[package]
name = "powork"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spaceframe-ledger = { path = "../ledger" }
borsh = "0.9.1"
sha2 = "0.9.5"
digest = "0.9.0"
hex = "0.4.3"